/* soapH.h
   Generated by gSOAP 2.8.3 from enrima.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_begin_send(soap) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__mathType
#define SOAP_TYPE_ns2__mathType (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__mathType(struct soap*, enum ns2__mathType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__mathType(struct soap*, const char*, int, const enum ns2__mathType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__mathType2s(struct soap*, enum ns2__mathType);
SOAP_FMAC3 enum ns2__mathType * SOAP_FMAC4 soap_in_ns2__mathType(struct soap*, const char*, enum ns2__mathType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__mathType(struct soap*, const char*, enum ns2__mathType *);

#ifndef soap_write_ns2__mathType
#define soap_write_ns2__mathType(soap, data) ( soap_begin_send(soap) || soap_put_ns2__mathType(soap, data, "ns2:mathType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__mathType(struct soap*, const enum ns2__mathType *, const char*, const char*);

#ifndef soap_read_ns2__mathType
#define soap_read_ns2__mathType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__mathType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum ns2__mathType * SOAP_FMAC4 soap_get_ns2__mathType(struct soap*, enum ns2__mathType *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__entityRole
#define SOAP_TYPE_ns2__entityRole (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__entityRole(struct soap*, enum ns2__entityRole *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__entityRole(struct soap*, const char*, int, const enum ns2__entityRole *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__entityRole2s(struct soap*, enum ns2__entityRole);
SOAP_FMAC3 enum ns2__entityRole * SOAP_FMAC4 soap_in_ns2__entityRole(struct soap*, const char*, enum ns2__entityRole *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__entityRole(struct soap*, const char*, enum ns2__entityRole *);

#ifndef soap_write_ns2__entityRole
#define soap_write_ns2__entityRole(soap, data) ( soap_begin_send(soap) || soap_put_ns2__entityRole(soap, data, "ns2:entityRole", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__entityRole(struct soap*, const enum ns2__entityRole *, const char*, const char*);

#ifndef soap_read_ns2__entityRole
#define soap_read_ns2__entityRole(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__entityRole(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum ns2__entityRole * SOAP_FMAC4 soap_get_ns2__entityRole(struct soap*, enum ns2__entityRole *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__setType
#define SOAP_TYPE_ns2__setType (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__setType(struct soap*, enum ns2__setType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__setType(struct soap*, const char*, int, const enum ns2__setType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__setType2s(struct soap*, enum ns2__setType);
SOAP_FMAC3 enum ns2__setType * SOAP_FMAC4 soap_in_ns2__setType(struct soap*, const char*, enum ns2__setType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__setType(struct soap*, const char*, enum ns2__setType *);

#ifndef soap_write_ns2__setType
#define soap_write_ns2__setType(soap, data) ( soap_begin_send(soap) || soap_put_ns2__setType(soap, data, "ns2:setType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__setType(struct soap*, const enum ns2__setType *, const char*, const char*);

#ifndef soap_read_ns2__setType
#define soap_read_ns2__setType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__setType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum ns2__setType * SOAP_FMAC4 soap_get_ns2__setType(struct soap*, enum ns2__setType *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__status
#define SOAP_TYPE_ns2__status (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__status(struct soap*, enum ns2__status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__status(struct soap*, const char*, int, const enum ns2__status *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__status2s(struct soap*, enum ns2__status);
SOAP_FMAC3 enum ns2__status * SOAP_FMAC4 soap_in_ns2__status(struct soap*, const char*, enum ns2__status *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__status(struct soap*, const char*, enum ns2__status *);

#ifndef soap_write_ns2__status
#define soap_write_ns2__status(soap, data) ( soap_begin_send(soap) || soap_put_ns2__status(soap, data, "ns2:status", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__status(struct soap*, const enum ns2__status *, const char*, const char*);

#ifndef soap_read_ns2__status
#define soap_read_ns2__status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__status(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum ns2__status * SOAP_FMAC4 soap_get_ns2__status(struct soap*, enum ns2__status *, const char*, const char*);

#ifndef SOAP_TYPE__ns2__saveModelDescriptionResponse
#define SOAP_TYPE__ns2__saveModelDescriptionResponse (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__saveModelDescriptionResponse(struct soap*, const char*, int, const _ns2__saveModelDescriptionResponse *, const char*);
SOAP_FMAC3 _ns2__saveModelDescriptionResponse * SOAP_FMAC4 soap_in__ns2__saveModelDescriptionResponse(struct soap*, const char*, _ns2__saveModelDescriptionResponse *, const char*);

#ifndef soap_write__ns2__saveModelDescriptionResponse
#define soap_write__ns2__saveModelDescriptionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:saveModelDescriptionResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__saveModelDescriptionResponse
#define soap_read__ns2__saveModelDescriptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__saveModelDescriptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__saveModelDescriptionResponse * SOAP_FMAC4 soap_get__ns2__saveModelDescriptionResponse(struct soap*, _ns2__saveModelDescriptionResponse *, const char*, const char*);

#define soap_new__ns2__saveModelDescriptionResponse(soap, n) soap_instantiate__ns2__saveModelDescriptionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__saveModelDescriptionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__saveModelDescriptionResponse * SOAP_FMAC2 soap_instantiate__ns2__saveModelDescriptionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__saveModelDescriptionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__saveModelDescriptionRequest
#define SOAP_TYPE__ns2__saveModelDescriptionRequest (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__saveModelDescriptionRequest(struct soap*, const char*, int, const _ns2__saveModelDescriptionRequest *, const char*);
SOAP_FMAC3 _ns2__saveModelDescriptionRequest * SOAP_FMAC4 soap_in__ns2__saveModelDescriptionRequest(struct soap*, const char*, _ns2__saveModelDescriptionRequest *, const char*);

#ifndef soap_write__ns2__saveModelDescriptionRequest
#define soap_write__ns2__saveModelDescriptionRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:saveModelDescriptionRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__saveModelDescriptionRequest
#define soap_read__ns2__saveModelDescriptionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__saveModelDescriptionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__saveModelDescriptionRequest * SOAP_FMAC4 soap_get__ns2__saveModelDescriptionRequest(struct soap*, _ns2__saveModelDescriptionRequest *, const char*, const char*);

#define soap_new__ns2__saveModelDescriptionRequest(soap, n) soap_instantiate__ns2__saveModelDescriptionRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__saveModelDescriptionRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__saveModelDescriptionRequest * SOAP_FMAC2 soap_instantiate__ns2__saveModelDescriptionRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__saveModelDescriptionRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__getModelDescriptionResponse
#define SOAP_TYPE__ns2__getModelDescriptionResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__getModelDescriptionResponse(struct soap*, const char*, int, const _ns2__getModelDescriptionResponse *, const char*);
SOAP_FMAC3 _ns2__getModelDescriptionResponse * SOAP_FMAC4 soap_in__ns2__getModelDescriptionResponse(struct soap*, const char*, _ns2__getModelDescriptionResponse *, const char*);

#ifndef soap_write__ns2__getModelDescriptionResponse
#define soap_write__ns2__getModelDescriptionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:getModelDescriptionResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__getModelDescriptionResponse
#define soap_read__ns2__getModelDescriptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__getModelDescriptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__getModelDescriptionResponse * SOAP_FMAC4 soap_get__ns2__getModelDescriptionResponse(struct soap*, _ns2__getModelDescriptionResponse *, const char*, const char*);

#define soap_new__ns2__getModelDescriptionResponse(soap, n) soap_instantiate__ns2__getModelDescriptionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__getModelDescriptionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__getModelDescriptionResponse * SOAP_FMAC2 soap_instantiate__ns2__getModelDescriptionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__getModelDescriptionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__getModelDescriptionRequest
#define SOAP_TYPE__ns2__getModelDescriptionRequest (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__getModelDescriptionRequest(struct soap*, const char*, int, const _ns2__getModelDescriptionRequest *, const char*);
SOAP_FMAC3 _ns2__getModelDescriptionRequest * SOAP_FMAC4 soap_in__ns2__getModelDescriptionRequest(struct soap*, const char*, _ns2__getModelDescriptionRequest *, const char*);

#ifndef soap_write__ns2__getModelDescriptionRequest
#define soap_write__ns2__getModelDescriptionRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:getModelDescriptionRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__getModelDescriptionRequest
#define soap_read__ns2__getModelDescriptionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__getModelDescriptionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__getModelDescriptionRequest * SOAP_FMAC4 soap_get__ns2__getModelDescriptionRequest(struct soap*, _ns2__getModelDescriptionRequest *, const char*, const char*);

#define soap_new__ns2__getModelDescriptionRequest(soap, n) soap_instantiate__ns2__getModelDescriptionRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__getModelDescriptionRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__getModelDescriptionRequest * SOAP_FMAC2 soap_instantiate__ns2__getModelDescriptionRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__getModelDescriptionRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__getModelListResponse
#define SOAP_TYPE__ns2__getModelListResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__getModelListResponse(struct soap*, const char*, int, const _ns2__getModelListResponse *, const char*);
SOAP_FMAC3 _ns2__getModelListResponse * SOAP_FMAC4 soap_in__ns2__getModelListResponse(struct soap*, const char*, _ns2__getModelListResponse *, const char*);

#ifndef soap_write__ns2__getModelListResponse
#define soap_write__ns2__getModelListResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:getModelListResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__getModelListResponse
#define soap_read__ns2__getModelListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__getModelListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__getModelListResponse * SOAP_FMAC4 soap_get__ns2__getModelListResponse(struct soap*, _ns2__getModelListResponse *, const char*, const char*);

#define soap_new__ns2__getModelListResponse(soap, n) soap_instantiate__ns2__getModelListResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__getModelListResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__getModelListResponse * SOAP_FMAC2 soap_instantiate__ns2__getModelListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__getModelListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__auditable
#define SOAP_TYPE_ns2__auditable (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__auditable(struct soap*, const char*, int, const ns2__auditable *, const char*);
SOAP_FMAC3 ns2__auditable * SOAP_FMAC4 soap_in_ns2__auditable(struct soap*, const char*, ns2__auditable *, const char*);

#ifndef soap_write_ns2__auditable
#define soap_write_ns2__auditable(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:auditable", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__auditable
#define soap_read_ns2__auditable(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__auditable(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__auditable * SOAP_FMAC4 soap_get_ns2__auditable(struct soap*, ns2__auditable *, const char*, const char*);

#define soap_new_ns2__auditable(soap, n) soap_instantiate_ns2__auditable(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__auditable(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__auditable * SOAP_FMAC2 soap_instantiate_ns2__auditable(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__auditable(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__user
#define SOAP_TYPE_ns2__user (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__user(struct soap*, const char*, int, const ns2__user *, const char*);
SOAP_FMAC3 ns2__user * SOAP_FMAC4 soap_in_ns2__user(struct soap*, const char*, ns2__user *, const char*);

#ifndef soap_write_ns2__user
#define soap_write_ns2__user(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:user", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__user
#define soap_read_ns2__user(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__user(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__user * SOAP_FMAC4 soap_get_ns2__user(struct soap*, ns2__user *, const char*, const char*);

#define soap_new_ns2__user(soap, n) soap_instantiate_ns2__user(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__user(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__user * SOAP_FMAC2 soap_instantiate_ns2__user(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__user(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__iteratorContainer
#define SOAP_TYPE_ns2__iteratorContainer (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__iteratorContainer(struct soap*, const char*, int, const ns2__iteratorContainer *, const char*);
SOAP_FMAC3 ns2__iteratorContainer * SOAP_FMAC4 soap_in_ns2__iteratorContainer(struct soap*, const char*, ns2__iteratorContainer *, const char*);

#ifndef soap_write_ns2__iteratorContainer
#define soap_write_ns2__iteratorContainer(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:iteratorContainer", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__iteratorContainer
#define soap_read_ns2__iteratorContainer(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__iteratorContainer(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__iteratorContainer * SOAP_FMAC4 soap_get_ns2__iteratorContainer(struct soap*, ns2__iteratorContainer *, const char*, const char*);

#define soap_new_ns2__iteratorContainer(soap, n) soap_instantiate_ns2__iteratorContainer(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__iteratorContainer(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__iteratorContainer * SOAP_FMAC2 soap_instantiate_ns2__iteratorContainer(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__iteratorContainer(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__entity
#define SOAP_TYPE_ns2__entity (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__entity(struct soap*, const char*, int, const ns2__entity *, const char*);
SOAP_FMAC3 ns2__entity * SOAP_FMAC4 soap_in_ns2__entity(struct soap*, const char*, ns2__entity *, const char*);

#ifndef soap_write_ns2__entity
#define soap_write_ns2__entity(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:entity", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__entity
#define soap_read_ns2__entity(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__entity(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__entity * SOAP_FMAC4 soap_get_ns2__entity(struct soap*, ns2__entity *, const char*, const char*);

#define soap_new_ns2__entity(soap, n) soap_instantiate_ns2__entity(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__entity(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__entity * SOAP_FMAC2 soap_instantiate_ns2__entity(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__entity(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__set
#define SOAP_TYPE_ns2__set (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__set(struct soap*, const char*, int, const ns2__set *, const char*);
SOAP_FMAC3 ns2__set * SOAP_FMAC4 soap_in_ns2__set(struct soap*, const char*, ns2__set *, const char*);

#ifndef soap_write_ns2__set
#define soap_write_ns2__set(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:set", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__set
#define soap_read_ns2__set(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__set(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__set * SOAP_FMAC4 soap_get_ns2__set(struct soap*, ns2__set *, const char*, const char*);

#define soap_new_ns2__set(soap, n) soap_instantiate_ns2__set(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__set(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__set * SOAP_FMAC2 soap_instantiate_ns2__set(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__set(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__modelRev
#define SOAP_TYPE_ns2__modelRev (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__modelRev(struct soap*, const char*, int, const ns2__modelRev *, const char*);
SOAP_FMAC3 ns2__modelRev * SOAP_FMAC4 soap_in_ns2__modelRev(struct soap*, const char*, ns2__modelRev *, const char*);

#ifndef soap_write_ns2__modelRev
#define soap_write_ns2__modelRev(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:modelRev", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__modelRev
#define soap_read_ns2__modelRev(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__modelRev(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__modelRev * SOAP_FMAC4 soap_get_ns2__modelRev(struct soap*, ns2__modelRev *, const char*, const char*);

#define soap_new_ns2__modelRev(soap, n) soap_instantiate_ns2__modelRev(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__modelRev(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__modelRev * SOAP_FMAC2 soap_instantiate_ns2__modelRev(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__modelRev(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__model
#define SOAP_TYPE_ns2__model (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__model(struct soap*, const char*, int, const ns2__model *, const char*);
SOAP_FMAC3 ns2__model * SOAP_FMAC4 soap_in_ns2__model(struct soap*, const char*, ns2__model *, const char*);

#ifndef soap_write_ns2__model
#define soap_write_ns2__model(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:model", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns2__model
#define soap_read_ns2__model(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__model(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__model * SOAP_FMAC4 soap_get_ns2__model(struct soap*, ns2__model *, const char*, const char*);

#define soap_new_ns2__model(soap, n) soap_instantiate_ns2__model(soap, n, NULL, NULL, NULL)


#define soap_delete_ns2__model(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns2__model * SOAP_FMAC2 soap_instantiate_ns2__model(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__model(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (9)
#endif

#define soap_default_xsd__date(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__date(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__date(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__date(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_xsd__date
#define soap_write_xsd__date(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:date", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__date(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_xsd__date
#define soap_read_xsd__date(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__date(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__date(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__date(soap, n) soap_instantiate_xsd__date(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__date(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__date soap_instantiate_std__string


#define soap_copy_xsd__date soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__getModelList
#define SOAP_TYPE___ns1__getModelList (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getModelList(struct soap*, struct __ns1__getModelList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getModelList(struct soap*, const struct __ns1__getModelList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getModelList(struct soap*, const char*, int, const struct __ns1__getModelList *, const char*);
SOAP_FMAC3 struct __ns1__getModelList * SOAP_FMAC4 soap_in___ns1__getModelList(struct soap*, const char*, struct __ns1__getModelList *, const char*);

#ifndef soap_write___ns1__getModelList
#define soap_write___ns1__getModelList(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__getModelList(soap, data), 0) || soap_put___ns1__getModelList(soap, data, "-ns1:getModelList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getModelList(struct soap*, const struct __ns1__getModelList *, const char*, const char*);

#ifndef soap_read___ns1__getModelList
#define soap_read___ns1__getModelList(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getModelList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__getModelList * SOAP_FMAC4 soap_get___ns1__getModelList(struct soap*, struct __ns1__getModelList *, const char*, const char*);

#define soap_new___ns1__getModelList(soap, n) soap_instantiate___ns1__getModelList(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__getModelList(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__getModelList * SOAP_FMAC2 soap_instantiate___ns1__getModelList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getModelList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__saveModelDescription
#define SOAP_TYPE___ns1__saveModelDescription (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__saveModelDescription(struct soap*, struct __ns1__saveModelDescription *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__saveModelDescription(struct soap*, const struct __ns1__saveModelDescription *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__saveModelDescription(struct soap*, const char*, int, const struct __ns1__saveModelDescription *, const char*);
SOAP_FMAC3 struct __ns1__saveModelDescription * SOAP_FMAC4 soap_in___ns1__saveModelDescription(struct soap*, const char*, struct __ns1__saveModelDescription *, const char*);

#ifndef soap_write___ns1__saveModelDescription
#define soap_write___ns1__saveModelDescription(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__saveModelDescription(soap, data), 0) || soap_put___ns1__saveModelDescription(soap, data, "-ns1:saveModelDescription", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__saveModelDescription(struct soap*, const struct __ns1__saveModelDescription *, const char*, const char*);

#ifndef soap_read___ns1__saveModelDescription
#define soap_read___ns1__saveModelDescription(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__saveModelDescription(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__saveModelDescription * SOAP_FMAC4 soap_get___ns1__saveModelDescription(struct soap*, struct __ns1__saveModelDescription *, const char*, const char*);

#define soap_new___ns1__saveModelDescription(soap, n) soap_instantiate___ns1__saveModelDescription(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__saveModelDescription(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__saveModelDescription * SOAP_FMAC2 soap_instantiate___ns1__saveModelDescription(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__saveModelDescription(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getModelDescription
#define SOAP_TYPE___ns1__getModelDescription (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getModelDescription(struct soap*, struct __ns1__getModelDescription *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getModelDescription(struct soap*, const struct __ns1__getModelDescription *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getModelDescription(struct soap*, const char*, int, const struct __ns1__getModelDescription *, const char*);
SOAP_FMAC3 struct __ns1__getModelDescription * SOAP_FMAC4 soap_in___ns1__getModelDescription(struct soap*, const char*, struct __ns1__getModelDescription *, const char*);

#ifndef soap_write___ns1__getModelDescription
#define soap_write___ns1__getModelDescription(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__getModelDescription(soap, data), 0) || soap_put___ns1__getModelDescription(soap, data, "-ns1:getModelDescription", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getModelDescription(struct soap*, const struct __ns1__getModelDescription *, const char*, const char*);

#ifndef soap_read___ns1__getModelDescription
#define soap_read___ns1__getModelDescription(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getModelDescription(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__getModelDescription * SOAP_FMAC4 soap_get___ns1__getModelDescription(struct soap*, struct __ns1__getModelDescription *, const char*, const char*);

#define soap_new___ns1__getModelDescription(soap, n) soap_instantiate___ns1__getModelDescription(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__getModelDescription(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__getModelDescription * SOAP_FMAC2 soap_instantiate___ns1__getModelDescription(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getModelDescription(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns2__getModelListResponse
#define SOAP_TYPE_PointerTo_ns2__getModelListResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__getModelListResponse(struct soap*, _ns2__getModelListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__getModelListResponse(struct soap*, const char *, int, _ns2__getModelListResponse *const*, const char *);
SOAP_FMAC3 _ns2__getModelListResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__getModelListResponse(struct soap*, const char*, _ns2__getModelListResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__getModelListResponse
#define soap_write_PointerTo_ns2__getModelListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__getModelListResponse(soap, data), 0) || soap_put_PointerTo_ns2__getModelListResponse(soap, data, "ns2:getModelListResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__getModelListResponse(struct soap*, _ns2__getModelListResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__getModelListResponse
#define soap_read_PointerTo_ns2__getModelListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__getModelListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__getModelListResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__getModelListResponse(struct soap*, _ns2__getModelListResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__saveModelDescriptionResponse
#define SOAP_TYPE_PointerTo_ns2__saveModelDescriptionResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__saveModelDescriptionResponse(struct soap*, _ns2__saveModelDescriptionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__saveModelDescriptionResponse(struct soap*, const char *, int, _ns2__saveModelDescriptionResponse *const*, const char *);
SOAP_FMAC3 _ns2__saveModelDescriptionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__saveModelDescriptionResponse(struct soap*, const char*, _ns2__saveModelDescriptionResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__saveModelDescriptionResponse
#define soap_write_PointerTo_ns2__saveModelDescriptionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__saveModelDescriptionResponse(soap, data), 0) || soap_put_PointerTo_ns2__saveModelDescriptionResponse(soap, data, "ns2:saveModelDescriptionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__saveModelDescriptionResponse(struct soap*, _ns2__saveModelDescriptionResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__saveModelDescriptionResponse
#define soap_read_PointerTo_ns2__saveModelDescriptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__saveModelDescriptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__saveModelDescriptionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__saveModelDescriptionResponse(struct soap*, _ns2__saveModelDescriptionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__saveModelDescriptionRequest
#define SOAP_TYPE_PointerTo_ns2__saveModelDescriptionRequest (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__saveModelDescriptionRequest(struct soap*, _ns2__saveModelDescriptionRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__saveModelDescriptionRequest(struct soap*, const char *, int, _ns2__saveModelDescriptionRequest *const*, const char *);
SOAP_FMAC3 _ns2__saveModelDescriptionRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__saveModelDescriptionRequest(struct soap*, const char*, _ns2__saveModelDescriptionRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__saveModelDescriptionRequest
#define soap_write_PointerTo_ns2__saveModelDescriptionRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__saveModelDescriptionRequest(soap, data), 0) || soap_put_PointerTo_ns2__saveModelDescriptionRequest(soap, data, "ns2:saveModelDescriptionRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__saveModelDescriptionRequest(struct soap*, _ns2__saveModelDescriptionRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__saveModelDescriptionRequest
#define soap_read_PointerTo_ns2__saveModelDescriptionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__saveModelDescriptionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__saveModelDescriptionRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__saveModelDescriptionRequest(struct soap*, _ns2__saveModelDescriptionRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__getModelDescriptionResponse
#define SOAP_TYPE_PointerTo_ns2__getModelDescriptionResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__getModelDescriptionResponse(struct soap*, _ns2__getModelDescriptionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__getModelDescriptionResponse(struct soap*, const char *, int, _ns2__getModelDescriptionResponse *const*, const char *);
SOAP_FMAC3 _ns2__getModelDescriptionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__getModelDescriptionResponse(struct soap*, const char*, _ns2__getModelDescriptionResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__getModelDescriptionResponse
#define soap_write_PointerTo_ns2__getModelDescriptionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__getModelDescriptionResponse(soap, data), 0) || soap_put_PointerTo_ns2__getModelDescriptionResponse(soap, data, "ns2:getModelDescriptionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__getModelDescriptionResponse(struct soap*, _ns2__getModelDescriptionResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__getModelDescriptionResponse
#define soap_read_PointerTo_ns2__getModelDescriptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__getModelDescriptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__getModelDescriptionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__getModelDescriptionResponse(struct soap*, _ns2__getModelDescriptionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__getModelDescriptionRequest
#define SOAP_TYPE_PointerTo_ns2__getModelDescriptionRequest (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__getModelDescriptionRequest(struct soap*, _ns2__getModelDescriptionRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__getModelDescriptionRequest(struct soap*, const char *, int, _ns2__getModelDescriptionRequest *const*, const char *);
SOAP_FMAC3 _ns2__getModelDescriptionRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__getModelDescriptionRequest(struct soap*, const char*, _ns2__getModelDescriptionRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__getModelDescriptionRequest
#define soap_write_PointerTo_ns2__getModelDescriptionRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__getModelDescriptionRequest(soap, data), 0) || soap_put_PointerTo_ns2__getModelDescriptionRequest(soap, data, "ns2:getModelDescriptionRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__getModelDescriptionRequest(struct soap*, _ns2__getModelDescriptionRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__getModelDescriptionRequest
#define soap_read_PointerTo_ns2__getModelDescriptionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__getModelDescriptionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__getModelDescriptionRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__getModelDescriptionRequest(struct soap*, _ns2__getModelDescriptionRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__model
#define SOAP_TYPE_PointerTons2__model (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__model(struct soap*, ns2__model *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__model(struct soap*, const char *, int, ns2__model *const*, const char *);
SOAP_FMAC3 ns2__model ** SOAP_FMAC4 soap_in_PointerTons2__model(struct soap*, const char*, ns2__model **, const char*);

#ifndef soap_write_PointerTons2__model
#define soap_write_PointerTons2__model(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__model(soap, data), 0) || soap_put_PointerTons2__model(soap, data, "ns2:model", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__model(struct soap*, ns2__model *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__model
#define soap_read_PointerTons2__model(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__model(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__model ** SOAP_FMAC4 soap_get_PointerTons2__model(struct soap*, ns2__model **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__user
#define SOAP_TYPE_PointerTons2__user (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__user(struct soap*, ns2__user *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__user(struct soap*, const char *, int, ns2__user *const*, const char *);
SOAP_FMAC3 ns2__user ** SOAP_FMAC4 soap_in_PointerTons2__user(struct soap*, const char*, ns2__user **, const char*);

#ifndef soap_write_PointerTons2__user
#define soap_write_PointerTons2__user(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__user(soap, data), 0) || soap_put_PointerTons2__user(soap, data, "ns2:user", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__user(struct soap*, ns2__user *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__user
#define soap_read_PointerTons2__user(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__user(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__user ** SOAP_FMAC4 soap_get_PointerTons2__user(struct soap*, ns2__user **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__iteratorContainer
#define SOAP_TYPE_PointerTons2__iteratorContainer (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__iteratorContainer(struct soap*, ns2__iteratorContainer *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__iteratorContainer(struct soap*, const char *, int, ns2__iteratorContainer *const*, const char *);
SOAP_FMAC3 ns2__iteratorContainer ** SOAP_FMAC4 soap_in_PointerTons2__iteratorContainer(struct soap*, const char*, ns2__iteratorContainer **, const char*);

#ifndef soap_write_PointerTons2__iteratorContainer
#define soap_write_PointerTons2__iteratorContainer(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__iteratorContainer(soap, data), 0) || soap_put_PointerTons2__iteratorContainer(soap, data, "ns2:iteratorContainer", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__iteratorContainer(struct soap*, ns2__iteratorContainer *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__iteratorContainer
#define soap_read_PointerTons2__iteratorContainer(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__iteratorContainer(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__iteratorContainer ** SOAP_FMAC4 soap_get_PointerTons2__iteratorContainer(struct soap*, ns2__iteratorContainer **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__entity
#define SOAP_TYPE_PointerTons2__entity (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__entity(struct soap*, ns2__entity *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__entity(struct soap*, const char *, int, ns2__entity *const*, const char *);
SOAP_FMAC3 ns2__entity ** SOAP_FMAC4 soap_in_PointerTons2__entity(struct soap*, const char*, ns2__entity **, const char*);

#ifndef soap_write_PointerTons2__entity
#define soap_write_PointerTons2__entity(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__entity(soap, data), 0) || soap_put_PointerTons2__entity(soap, data, "ns2:entity", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__entity(struct soap*, ns2__entity *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__entity
#define soap_read_PointerTons2__entity(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__entity(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__entity ** SOAP_FMAC4 soap_get_PointerTons2__entity(struct soap*, ns2__entity **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__set
#define SOAP_TYPE_PointerTons2__set (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__set(struct soap*, ns2__set *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__set(struct soap*, const char *, int, ns2__set *const*, const char *);
SOAP_FMAC3 ns2__set ** SOAP_FMAC4 soap_in_PointerTons2__set(struct soap*, const char*, ns2__set **, const char*);

#ifndef soap_write_PointerTons2__set
#define soap_write_PointerTons2__set(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__set(soap, data), 0) || soap_put_PointerTons2__set(soap, data, "ns2:set", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__set(struct soap*, ns2__set *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__set
#define soap_read_PointerTons2__set(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__set(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__set ** SOAP_FMAC4 soap_get_PointerTons2__set(struct soap*, ns2__set **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__modelRev
#define SOAP_TYPE_PointerTons2__modelRev (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__modelRev(struct soap*, ns2__modelRev *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__modelRev(struct soap*, const char *, int, ns2__modelRev *const*, const char *);
SOAP_FMAC3 ns2__modelRev ** SOAP_FMAC4 soap_in_PointerTons2__modelRev(struct soap*, const char*, ns2__modelRev **, const char*);

#ifndef soap_write_PointerTons2__modelRev
#define soap_write_PointerTons2__modelRev(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__modelRev(soap, data), 0) || soap_put_PointerTons2__modelRev(soap, data, "ns2:modelRev", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__modelRev(struct soap*, ns2__modelRev *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__modelRev
#define soap_read_PointerTons2__modelRev(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__modelRev(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__modelRev ** SOAP_FMAC4 soap_get_PointerTons2__modelRev(struct soap*, ns2__modelRev **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__auditable
#define SOAP_TYPE_PointerTons2__auditable (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__auditable(struct soap*, ns2__auditable *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__auditable(struct soap*, const char *, int, ns2__auditable *const*, const char *);
SOAP_FMAC3 ns2__auditable ** SOAP_FMAC4 soap_in_PointerTons2__auditable(struct soap*, const char*, ns2__auditable **, const char*);

#ifndef soap_write_PointerTons2__auditable
#define soap_write_PointerTons2__auditable(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__auditable(soap, data), 0) || soap_put_PointerTons2__auditable(soap, data, "ns2:auditable", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__auditable(struct soap*, ns2__auditable *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__auditable
#define soap_read_PointerTons2__auditable(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__auditable(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns2__auditable ** SOAP_FMAC4 soap_get_PointerTons2__auditable(struct soap*, ns2__auditable **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__model
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__model (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__model(struct soap*, std::vector<ns2__model * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__model(struct soap*, const std::vector<ns2__model * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__model(struct soap*, const char*, int, const std::vector<ns2__model * >*, const char*);
SOAP_FMAC3 std::vector<ns2__model * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__model(struct soap*, const char*, std::vector<ns2__model * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons2__model(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons2__model(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons2__model(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<ns2__model * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons2__model(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__model(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfint
#define SOAP_TYPE_std__vectorTemplateOfint (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfint(struct soap*, std::vector<int >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfint(struct soap*, const std::vector<int >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfint(struct soap*, const char*, int, const std::vector<int >*, const char*);
SOAP_FMAC3 std::vector<int >* SOAP_FMAC4 soap_in_std__vectorTemplateOfint(struct soap*, const char*, std::vector<int >*, const char*);

#define soap_new_std__vectorTemplateOfint(soap, n) soap_instantiate_std__vectorTemplateOfint(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfint(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<int > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfint(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfint(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__entity
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__entity (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__entity(struct soap*, std::vector<ns2__entity * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__entity(struct soap*, const std::vector<ns2__entity * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__entity(struct soap*, const char*, int, const std::vector<ns2__entity * >*, const char*);
SOAP_FMAC3 std::vector<ns2__entity * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__entity(struct soap*, const char*, std::vector<ns2__entity * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons2__entity(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons2__entity(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons2__entity(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<ns2__entity * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons2__entity(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__entity(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__set
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__set (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__set(struct soap*, std::vector<ns2__set * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__set(struct soap*, const std::vector<ns2__set * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__set(struct soap*, const char*, int, const std::vector<ns2__set * >*, const char*);
SOAP_FMAC3 std::vector<ns2__set * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__set(struct soap*, const char*, std::vector<ns2__set * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons2__set(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons2__set(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons2__set(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<ns2__set * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons2__set(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__set(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__modelRev
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__modelRev (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__modelRev(struct soap*, std::vector<ns2__modelRev * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__modelRev(struct soap*, const std::vector<ns2__modelRev * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__modelRev(struct soap*, const char*, int, const std::vector<ns2__modelRev * >*, const char*);
SOAP_FMAC3 std::vector<ns2__modelRev * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__modelRev(struct soap*, const char*, std::vector<ns2__modelRev * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons2__modelRev(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons2__modelRev(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons2__modelRev(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<ns2__modelRev * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons2__modelRev(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__modelRev(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
