/* soapenrimaSoap11Proxy.cpp
   Generated by gSOAP 2.8.3 from enrima.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapenrimaSoap11Proxy.h"

enrimaSoap11Proxy::enrimaSoap11Proxy()
{	enrimaSoap11Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

enrimaSoap11Proxy::enrimaSoap11Proxy(const struct soap &_soap) : soap(_soap)
{ }

enrimaSoap11Proxy::enrimaSoap11Proxy(const char *url)
{	enrimaSoap11Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

enrimaSoap11Proxy::enrimaSoap11Proxy(soap_mode iomode)
{	enrimaSoap11Proxy_init(iomode, iomode);
}

enrimaSoap11Proxy::enrimaSoap11Proxy(const char *url, soap_mode iomode)
{	enrimaSoap11Proxy_init(iomode, iomode);
	soap_endpoint = url;
}

enrimaSoap11Proxy::enrimaSoap11Proxy(soap_mode imode, soap_mode omode)
{	enrimaSoap11Proxy_init(imode, omode);
}

enrimaSoap11Proxy::~enrimaSoap11Proxy()
{ }

void enrimaSoap11Proxy::enrimaSoap11Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://ime.iiasa.ac.at/enrima/example", NULL, NULL},
	{"ns2", "http://www.ime.iiasa.ac.at/enrima/model/example", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void enrimaSoap11Proxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void enrimaSoap11Proxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *enrimaSoap11Proxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *enrimaSoap11Proxy::soap_fault()
{	return this->fault;
}

const char *enrimaSoap11Proxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *enrimaSoap11Proxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int enrimaSoap11Proxy::soap_close_socket()
{	return soap_closesock(this);
}

void enrimaSoap11Proxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void enrimaSoap11Proxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *enrimaSoap11Proxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int enrimaSoap11Proxy::getModelDescription(const char *endpoint, const char *soap_action, _ns2__getModelDescriptionRequest *ns2__getModelDescriptionRequest, _ns2__getModelDescriptionResponse *ns2__getModelDescriptionResponse)
{	struct soap *soap = this;
	struct __ns1__getModelDescription soap_tmp___ns1__getModelDescription;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/enrima/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getModelDescription.ns2__getModelDescriptionRequest = ns2__getModelDescriptionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getModelDescription(soap, &soap_tmp___ns1__getModelDescription);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getModelDescription(soap, &soap_tmp___ns1__getModelDescription, "-ns1:getModelDescription", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getModelDescription(soap, &soap_tmp___ns1__getModelDescription, "-ns1:getModelDescription", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__getModelDescriptionResponse)
		return soap_closesock(soap);
	ns2__getModelDescriptionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__getModelDescriptionResponse->soap_get(soap, "ns2:getModelDescriptionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::saveModelDescription(const char *endpoint, const char *soap_action, _ns2__saveModelDescriptionRequest *ns2__saveModelDescriptionRequest, _ns2__saveModelDescriptionResponse *ns2__saveModelDescriptionResponse)
{	struct soap *soap = this;
	struct __ns1__saveModelDescription soap_tmp___ns1__saveModelDescription;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/enrima/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__saveModelDescription.ns2__saveModelDescriptionRequest = ns2__saveModelDescriptionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__saveModelDescription(soap, &soap_tmp___ns1__saveModelDescription);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__saveModelDescription(soap, &soap_tmp___ns1__saveModelDescription, "-ns1:saveModelDescription", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__saveModelDescription(soap, &soap_tmp___ns1__saveModelDescription, "-ns1:saveModelDescription", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__saveModelDescriptionResponse)
		return soap_closesock(soap);
	ns2__saveModelDescriptionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__saveModelDescriptionResponse->soap_get(soap, "ns2:saveModelDescriptionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int enrimaSoap11Proxy::getModelList(const char *endpoint, const char *soap_action, char *ns2__getModelListRequest, _ns2__getModelListResponse *ns2__getModelListResponse)
{	struct soap *soap = this;
	struct __ns1__getModelList soap_tmp___ns1__getModelList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://www.ime.iiasa.ac.at:80/enrima_ws_tst1/enrima/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getModelList.ns2__getModelListRequest = ns2__getModelListRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getModelList(soap, &soap_tmp___ns1__getModelList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getModelList(soap, &soap_tmp___ns1__getModelList, "-ns1:getModelList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getModelList(soap, &soap_tmp___ns1__getModelList, "-ns1:getModelList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__getModelListResponse)
		return soap_closesock(soap);
	ns2__getModelListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__getModelListResponse->soap_get(soap, "ns2:getModelListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
